name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Vérifier le code source
      uses: actions/checkout@v4
    
    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Installer les dépendances et télécharger les fichiers
      run: |
        pip install pandas plotly
        curl -o hadcrutworld.csv https://raw.githubusercontent.com/alanjones2/CO2/master/data/world_df.csv
        curl -o globaltemp.csv https://raw.githubusercontent.com/alanjones2/GISS/main/data/GLB.Ts%2BdSST.csv